local base = require('ayugloom.base')
local lush = require('lush')

return lush(function()
  return {
    -- Bar Context
    DropBarCurrentContext({ base.Visual }),

    -- DropBarFzfMatch({ base.TelescopeMatching }),
    DropBarHover({ base.Visual }),
    DropBarIconCurrentContext({ base.Visual }),

    -- Menu
    DropBarMenuCurrentContext({ base.PmenuSel }),
    DropBarMenuFloatBorder({ base.FloatBorder }),
    DropBarMenuHoverEntry({ base.Visual }),
    DropBarMenuHoverIcon({ reverse = false }),
    DropBarMenuHoverSymbol({ bold = true }),
    DropBarMenuNormalFloat({ base.NormalFloat }),
    DropBarMenuSbar({ base.Visual }),
    DropBarMenuThumb({ base.Visual }),
    DropBarPreview({ base.Visual }),

    -- UI Icon
    DropBarIconUIIndicator({ base.Directory }),
    DropBarIconUIPickPivot({ fg = base.Substitute.bg }),
    DropBarIconUISeparator({ base.Directory }),
    DropBarIconUISeparatorMenu({ base.Directory }),

    -- Icon
    DropBarIconKindArray({ base.Array }),
    DropBarIconKindBoolean({ base.Boolean }),
    DropBarIconKindBreakStatement({ base.Error }),
    DropBarIconKindCall({ base.Function }),
    DropBarIconKindCaseStatement({ base.Conditional }),
    DropBarIconKindClass({ base.CmpItemKindClass }),
    DropBarIconKindConstant({ base.Constant }),
    DropBarIconKindConstructor({ base.CmpItemKindConstructor }),
    DropBarIconKindContinueStatement({ base.Repeat }),
    DropBarIconKindDeclaration({ base.CmpItemKindSnippet }),
    DropBarIconKindDelete({ base.Error }),
    DropBarIconKindDoStatement({ base.Repeat }),
    DropBarIconKindElseStatement({ base.Conditional }),
    DropBarIconKindEnum({ base.CmpItemKindEnum }),
    DropBarIconKindEnumMember({ base.CmpItemKindEnumMember }),
    DropBarIconKindEvent({ base.CmpItemKindEvent }),
    DropBarIconKindField({ base.CmpItemKindField }),
    DropBarIconKindFile({ base.NormalFloat }),
    DropBarIconKindFolder({ base.Directory }),
    DropBarIconKindForStatement({ base.Repeat }),
    DropBarIconKindFunction({ base.Function }),
    DropBarIconKindH1Marker({ base.markdownH1 }),
    DropBarIconKindH2Marker({ base.markdownH2 }),
    DropBarIconKindH3Marker({ base.markdownH3 }),
    DropBarIconKindH4Marker({ base.markdownH4 }),
    DropBarIconKindH5Marker({ base.markdownH5 }),
    DropBarIconKindH6Marker({ base.markdownH6 }),
    DropBarIconKindIdentifier({ base.CmpItemKindVariable }),
    DropBarIconKindIfStatement({ base.Conditional }),
    DropBarIconKindInterface({ base.CmpItemKindInterface }),
    DropBarIconKindKeyword({ base.Keyword }),
    DropBarIconKindList({ base.SpecialChar }),
    DropBarIconKindMacro({ base.Macro }),
    DropBarIconKindMarkdownH1({ base.markdownH1 }),
    DropBarIconKindMarkdownH2({ base.markdownH2 }),
    DropBarIconKindMarkdownH3({ base.markdownH3 }),
    DropBarIconKindMarkdownH4({ base.markdownH4 }),
    DropBarIconKindMarkdownH5({ base.markdownH5 }),
    DropBarIconKindMarkdownH6({ base.markdownH6 }),
    DropBarIconKindMethod({ base.CmpItemKindMethod }),
    DropBarIconKindModule({ base.CmpItemKindModule }),
    DropBarIconKindNamespace({ base.NameSpace }),
    DropBarIconKindNull({ base.Constant }),
    DropBarIconKindNumber({ base.Number }),
    DropBarIconKindObject({ base.Statement }),
    DropBarIconKindOperator({ base.Operator }),
    DropBarIconKindPackage({ base.CmpItemKindModule }),
    DropBarIconKindPair({ base.String }),
    DropBarIconKindProperty({ base.CmpItemKindProperty }),
    DropBarIconKindReference({ base.CmpItemKindReference }),
    DropBarIconKindRepeat({ base.Repeat }),
    DropBarIconKindScope({ base.NameSpace }),
    DropBarIconKindSpecifier({ base.Specifier }),
    DropBarIconKindStatement({ base.Statement }),
    DropBarIconKindString({ base.String }),
    DropBarIconKindStruct({ base.CmpItemKindStruct }),
    DropBarIconKindSwitchStatement({ base.Conditional }),
    DropBarIconKindTerminal({ base.Number }),
    DropBarIconKindType({ base.CmpItemKindClass }),
    DropBarIconKindTypeParameter({ base.CmpItemKindTypeParameter }),
    DropBarIconKindUnit({ base.CmpItemKindUnit }),
    DropBarIconKindValue({ base.Number }),
    DropBarIconKindVariable({ base.CmpItemKindVariable }),
    DropBarIconKindWhileStatement({ base.Repeat }),

    -- Kind
    DropBarKindArray({ DropBarIconKindArray }),
    DropBarKindBoolean({ DropBarIconKindBoolean }),
    DropBarKindBreakStatement({ DropBarIconKindBreakStatement }),
    DropBarKindCall({ DropBarIconKindCall }),
    DropBarKindCaseStatement({ DropBarIconKindCaseStatement }),
    DropBarKindClass({ DropBarIconKindClass }),
    DropBarKindConstant({ DropBarIconKindConstant }),
    DropBarKindConstructor({ DropBarIconKindConstructor }),
    DropBarKindContinueStatement({ DropBarIconKindContinueStatement }),
    DropBarKindDeclaration({ DropBarIconKindDeclaration }),
    DropBarKindDelete({ DropBarIconKindDelete }),
    DropBarKindDoStatement({ DropBarIconKindDoStatement }),
    DropBarKindElseStatement({ DropBarIconKindElseStatement }),
    DropBarKindEnum({ DropBarIconKindEnum }),
    DropBarKindEnumMember({ DropBarIconKindEnumMember }),
    DropBarKindEvent({ DropBarIconKindEvent }),
    DropBarKindField({ DropBarIconKindField }),
    DropBarKindFile({ DropBarIconKindFile }),
    DropBarKindFolder({ DropBarIconKindFolder }),
    DropBarKindForStatement({ DropBarIconKindForStatement }),
    DropBarKindFunction({ DropBarIconKindFunction }),
    DropBarKindIdentifier({ DropBarIconKindIdentifier }),
    DropBarKindIfStatement({ DropBarIconKindIfStatement }),
    DropBarKindInterface({ DropBarIconKindInterface }),
    DropBarKindKeyword({ DropBarIconKindKeyword }),
    DropBarKindList({ DropBarIconKindList }),
    DropBarKindMacro({ DropBarIconKindMacro }),
    DropBarKindMarkdownH1({ DropBarIconKindMarkdownH1 }),
    DropBarKindMarkdownH2({ DropBarIconKindMarkdownH2 }),
    DropBarKindMarkdownH3({ DropBarIconKindMarkdownH3 }),
    DropBarKindMarkdownH4({ DropBarIconKindMarkdownH4 }),
    DropBarKindMarkdownH5({ DropBarIconKindMarkdownH5 }),
    DropBarKindMarkdownH6({ DropBarIconKindMarkdownH6 }),
    DropBarKindMethod({ DropBarIconKindMethod }),
    DropBarKindModule({ DropBarIconKindModule }),
    DropBarKindNamespace({ DropBarIconKindNamespace }),
    DropBarKindNull({ DropBarIconKindNull }),
    DropBarKindNumber({ DropBarIconKindNumber }),
    DropBarKindObject({ DropBarIconKindObject }),
    DropBarKindOperator({ DropBarIconKindOperator }),
    DropBarKindPackage({ DropBarIconKindPackage }),
    DropBarKindProperty({ DropBarIconKindProperty }),
    DropBarKindReference({ DropBarIconKindReference }),
    DropBarKindRepeat({ DropBarIconKindRepeat }),
    DropBarKindScope({ DropBarIconKindScope }),
    DropBarKindSpecifier({ DropBarIconKindSpecifier }),
    DropBarKindStatement({ DropBarIconKindStatement }),
    DropBarKindString({ DropBarIconKindString }),
    DropBarKindStruct({ DropBarIconKindStruct }),
    DropBarKindSwitchStatement({ DropBarIconKindSwitchStatement }),
    DropBarKindType({ DropBarIconKindType }),
    DropBarKindTypeParameter({ DropBarIconKindTypeParameter }),
    DropBarKindUnit({ DropBarIconKindUnit }),
    DropBarKindValue({ DropBarIconKindValue }),
    DropBarKindVariable({ DropBarIconKindVariable }),
    DropBarKindWhileStatement({ DropBarIconKindWhileStatement }),
  }
end)
