local lush = require('lush')
local base = require('ayugloom.base')

return lush(function(injected_functions)
  local sym = injected_functions.sym
  return {

    -- NavbuddyCursor      { sym "@Cursor"      },
    -- NavbuddyFloatBorder { sym "@FloatBorder" },
    -- NavbuddyName        { sym "@Name"        },
    -- NavbuddyNormalFloat { sym "@NormalFloat" },
    -- NavbuddyScope       { sym "@scope"       },

    NavbuddyArray         { fg = sym"@punctuation".fg            },
    NavbuddyBoolean       { fg = sym"@boolean".fg                },
    NavbuddyClass         { fg = sym"@lsp.type.class".fg         },
    NavbuddyConstant      { fg = sym"@constant".fg               },
    NavbuddyConstructor   { fg = sym"@constructor".fg            },
    NavbuddyEnum          { fg = sym"@lsp.type.enum".fg          },
    NavbuddyEnumMember    { fg = sym"@lsp.type.enumMember".fg    },
    NavbuddyEvent         { fg = sym"@field".fg                  },
    NavbuddyField         { fg = sym"@field".fg                  },
    NavbuddyFunction      { fg = sym"@function".fg               },
    NavbuddyFile          { base.Normal                          },
    NavbuddyInterface     { fg = sym"@lsp.type.interface".fg     },
    NavbuddyKey           { fg = sym"@keyword".fg                },
    NavbuddyMethod        { fg = sym"@method".fg                 },
    NavbuddyModule        { fg = sym"@module".fg                 },
    NavbuddyNamespace     { fg = sym"@namespace".fg              },
    NavbuddyNull          { fg = sym"@constant".fg               },
    NavbuddyNumber        { fg = sym"@number".fg                 },
    NavbuddyObject        { fg = sym"@lsp.type.class".fg         },
    NavbuddyOperator      { fg = sym"@operator".fg               },
    NavbuddyPackage       { fg = sym"@namespace".fg              },
    NavbuddyProperty      { fg = sym"@parameter".fg              },
    NavbuddyString        { fg = sym"@string".fg                 },
    NavbuddyStruct        { fg = sym"@lsp.type.struct".fg        },
    NavbuddyTypeParameter { fg = sym"@lsp.type.typeParameter".fg },
    NavbuddyVariable      { fg = sym"@variable".fg               },


    -- NavbuddyCursorLine           { Navbuddy              },
    -- NavbuddyCursorLineArray         { NavbuddyArray         },
    -- NavbuddyCursorLineBoolean       { NavbuddyBoolean       },
    -- NavbuddyCursorLineClass         { NavbuddyClass         },
    -- NavbuddyCursorLineConstant      { NavbuddyConstant      },
    -- NavbuddyCursorLineConstructor   { NavbuddyConstructor   },
    -- NavbuddyCursorLineEnum          { NavbuddyEnum          },
    -- NavbuddyCursorLineEnumMember    { NavbuddyEnumMember    },
    -- NavbuddyCursorLineEvent         { NavbuddyEvent         },
    -- NavbuddyCursorLineField         { NavbuddyField         },
    -- NavbuddyCursorLineFile          { NavbuddyFile          },
    -- NavbuddyCursorLineFunction      { NavbuddyFunction      },
    -- NavbuddyCursorLineInterface     { NavbuddyInterface     },
    -- NavbuddyCursorLineKey           { NavbuddyKey           },
    -- NavbuddyCursorLineMethod        { NavbuddyMethod        },
    -- NavbuddyCursorLineModule        { NavbuddyModule        },
    -- NavbuddyCursorLineNamespace     { NavbuddyNamespace     },
    -- NavbuddyCursorLineNull          { NavbuddyNull          },
    -- NavbuddyCursorLineNumber        { NavbuddyNumber        },
    -- NavbuddyCursorLineObject        { NavbuddyObject        },
    -- NavbuddyCursorLineOperator      { NavbuddyOperator      },
    -- NavbuddyCursorLinePackage       { NavbuddyPackage       },
    -- NavbuddyCursorLineProperty      { NavbuddyProperty      },
    -- NavbuddyCursorLineString        { NavbuddyString        },
    -- NavbuddyCursorLineStruct        { NavbuddyStruct        },
    -- NavbuddyCursorLineTypeParameter { NavbuddyTypeParameter },
    -- NavbuddyCursorLineVariable      { NavbuddyVariable      },
  }
end)
